export const educationListElements_HU = [
    {
        id: 1,
        school: 'Mechatronikai Szakközépiskola és Gimnázium',
        level: 'Középiskola',
        techonology: '',
        location: 'Budapest, Magyarország',
        url: 'https://mechatronika.hu/',
        start: '2010/09',
        end: '2015/06',
    },
    {
        id: 2,
        school: 'BMSZC Petrik Lajos Informatikai Szakgimnázium',
        level: 'Szoftverfejlesztés OKJ - EKKR 5',
        techonology: 'PHP-SQL-HTML-CSS',
        location: 'Budapest, Magyarország',
        url: 'https://petrik.hu/',
        start: '2015/09',
        end: '2016/06',
    },
    {
        id: 3,
        school: 'Schola Europa Akadémia',
        level: 'Szoftverfejlesztés OKJ - EKKR 5',
        techonology: 'PHP-SQL-HTML-CSS',
        location: 'Budapest, Magyarország',
        url: 'http://www.schola.esa.hu/',
        start: '2019/09',
        end: '2020/05',
    },
];
export const educationListElements_ENG = [
    {
        id: 1,
        school: 'Mechatronikai Szakközépiskola és Gimnázium',
        level: 'Középiskola',
        techonology: '',
        location: 'Budapest, Magyarország',
        url: 'https://mechatronika.hu/',
        start: '2010/09',
        end: '2015/06',
    },
    {
        id: 2,
        school: 'BMSZC Petrik Lajos Két Tanítási Nyelvű Vegyipari, Környezetvédelmi és Informatikai Szakgimnázium',
        level: 'Szoftverfejlesztés OKJ - EKKR 5',
        techonology: 'PHP-SQL-HTML-CSS',
        location: 'Budapest, Magyarország',
        url: 'https://petrik.hu/',
        start: '2015/09',
        end: '2016/06',
    },
    {
        id: 3,
        school: 'Schola Europa Akadémia Hallgatóiért Közhasznú Alapítvány',
        level: 'Szoftverfejlesztés OKJ - EKKR 5',
        techonology: 'PHP-SQL-HTML-CSS',
        location: 'Budapest, Magyarország',
        url: 'http://www.schola.esa.hu/',
        start: '2019/09',
        end: '2020/05',
    },
];
